---
title: "Class4"
author: "Kyle Mahowald"
date: "4/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## This is a header

We ran a lexical decision experiment in Ling 104. Below, we read in the lexical decision data using the tidyverse. 

We create a new column ResidualRT which is the normalized RT for each subject, and we make a histogram of the ResidualRTs.

```{r reading, include=TRUE}
library(tidyverse)
d = read_csv("../experiments/lexdec.csv", comment = "#",
             col_names = c("time", "subj", "exp",
                           "item", "element", "type",
                           "garbage", "wordnum", 
                           "word", "RT", "guess", 
                           "Sent")) %>%
  filter(type != "words")

d = group_by(d, subj) %>%
  mutate(ResidualRT = (RT - mean(RT))/sd(RT))
hist(d$ResidualRT, breaks=40)
```

# Reviewing Tidyverse: Looking at the dative

```{r}
dative = read_csv("LING104/pset1/dative.csv")
```

# Learning ggplot

```{r}
```
